---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-abdevlab-xyz
  namespace: default
spec:
  secretName: local-abdevlab-xyz-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.abdevlab.xyz"
  dnsNames:
  - "local.abdevlab.xyz"
  - "*.local.abdevlab.xyz"