version: "2"
services: 
  app: 
    depends_on: 
      - db
    environment: 
      - MYSQL_PASSWORD=MYSQLPW
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=MYSQLUSER
      - MYSQL_HOST=db
    image: nextcloud
    links: 
      - db
    ports: 
      - "8080:80"
    restart: always
    volumes: 
      - "/home/docker/nextcloud/nextcloud:/var/www/html"
      - "/home/docker/nextcloud/app/custom_apps:/var/www/html/custom_apps"
      - "/home/docker/nextcloud/app/config:/var/www/html/config"
      - "/home/docker/nextcloud/app/themes:/var/www/html/data"
      - "/home/docker/nextcloud/app/themes:/var/www/html/themes"
  db: 
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW"
    environment: 
      - MYSQL_ROOT_PASSWORD=MYSQLROOTPW
      - MYSQL_PASSWORD=MYSQLPW
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=MYSQLUSER
    image: "mariadb:10.5"
    restart: always
    volumes: 
      - "/home/docker/nextcloud/db:/var/lib/mysql"