version: "3.8"

services:
  cloudflare-tunnel:
    container_name: cloudflare-tunnel
    image: ghcr.io/shmick/docker-cloudflared
    user: 1000:1000
    network_mode: host
    environment: 
      - TUNNEL_TOKEN
      - TUNNEL_METRICS
    command: tunnel run
    restart: unless-stopped