version: "3.8"

services:
 portainer:
    env_file:
      - ./.env
    image: portainer/portainer-ce
    container_name: "portainer"
    networks:
      - web
    labels:
      - traefik.backend=portainer
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls.certresolver=letsencrypt
      - traefik.frontend.rule=Host:${PORTAINER_HOST}
      - traefik.docker.network=web
      - traefik.port=9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/nfs/portainer_data:/data
    restart: unless-stopped

networks:
  web:
    external: